### ISSUE TITLE
Warning You may reach API Hard limit

### ISSUE THREAD

**Issue by yashodhank** [tekspry/openai-code-analyser#2]
This app iterate over all files under specified directory path to create following output
```
Code Review:
Positive Points: 
- The code is well-structured and easy to read.
- All the properties are declared with the appropriate data type.
- The code is using the latest version of .NET (EF Core).
- All the properties are declared with nullable reference types (NRTs).

Improvement Areas: 
- The code could be improved by adding more comments to explain the purpose of each property and its usage.
- The code could be improved by using more descriptive names for the properties and variables.
```

```
Positive Points:

- The code is well organized and easy to read. 
- The code is using System, so all the necessary components are included. 
- The code is using nullable reference types, which will help ensure that data is not lost due to null values. 
- The code is using partial classes, which allows for easier maintenance and scalability. 
- The code is using meaningful variable names, which will help with readability. 

Improvement Areas:

- The code could be improved by using more descriptive comments to explain the purpose of each line of code. 
- The code could be improved by adding more validation checks to ensure that data is not lost due to incorrect input. 
- The code could be improved by adding more logging to track changes and errors.
```

if there are lot of files you will quickly end up burning many API calls, essentially may also hit API usage hard limit. So be very careful.

**Comment by tekspry** [comment]
Hi Yash, to manage it flexibility is provided in the code to provide the custom path as parameter. 

<img width="256" alt="image" src="https://github.com/tekspry/openai-code-analyser/assets/110311110/70da8ff5-7a8c-4017-8b22-53644e36c54e">

Also there is a provision to exclude files in appsettings.json which are not required. 

<img width="143" alt="image" src="https://github.com/tekspry/openai-code-analyser/assets/110311110/737a22b6-6269-43cf-be58-e6c8bbf30db7">

we don't want to put any restriction from our end for the user on number of files they want to analyze.  User can take a decision which files they want to analyze and which one to skip.
